[features]
seeds = false
skip-lint = false

[programs.localnet]
zephyra_protection_manager = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
zephyra_route_executor = "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM"
zephyra_proof_verifier = "Cw8CFyM9FkoMi7KTYpkqXZ4e4v5X3sJ7W8dL2mN9pQrT"
zephyra_batch_coordinator = "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU"

[programs.devnet]
zephyra_protection_manager = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
zephyra_route_executor = "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM"
zephyra_proof_verifier = "Cw8CFyM9FkoMi7KTYpkqXZ4e4v5X3sJ7W8dL2mN9pQrT"
zephyra_batch_coordinator = "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU"

[programs.mainnet]
zephyra_protection_manager = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
zephyra_route_executor = "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM"
zephyra_proof_verifier = "Cw8CFyM9FkoMi7KTYpkqXZ4e4v5X3sJ7W8dL2mN9pQrT"
zephyra_batch_coordinator = "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

[toolchain]
anchor_version = "0.32.1"
solana_version = "1.18.26"

