[package]
name = "zephyra-proof-verifier"
version = "1.0.0"
description = "Zephyra Proof Verifier Program - Generate and verify cryptographic proofs"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "zephyra_proof_verifier"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.32.1"
anchor-spl = "0.32.1"
solana-program = "~1.18.2"



